theme: jekyll-theme-minimal
title: LT
description: Luca Trivellato's personal website, provided by GitHub Pages.
#domain: lucatrivellato.com
#url: https://www.lucatrivellato.com
#baseurl: /luktwe.github.io/